### ISSUE TITLE
Advisor Sign In

### ISSUE THREAD

**Issue by jackmoneyfitt** [Growthautomation/moneyfitt#134]
<img width="1437" alt="Screenshot 2024-10-29 at 15 16 55" src="https://github.com/user-attachments/assets/2079cc43-8f76-4c5e-bd83-baa7d5a8582a">

1. Put the login in the middle/centre

2. Change it from agent sign in to advisor sign in 

3. No forgot password option

**Comment by yeaung276** [comment]
commit: 62006a21df4d1a36ad66a7e996d5d398265867f3
