### ISSUE TITLE
Title vs Subtitle

### ISSUE THREAD

**Issue by jackmoneyfitt** [Growthautomation/moneyfitt#137]
<img width="1434" alt="Screenshot 2024-10-29 at 15 33 55" src="https://github.com/user-attachments/assets/ffc651d7-3ee1-4d17-91d7-32db2c5baea3">

Title: Your Financial Planning
Subtitle: Emergency Fund

We need to make it clear that one is the title and one is subtitle. 

Either make the subtitle thinner or smaller size font.

**Comment by MikeBorman1** [comment]
waiting on designer
