### ISSUE TITLE
URL

### ISSUE THREAD

**Issue by jackmoneyfitt** [Growthautomation/moneyfitt#139]
<img width="1171" alt="Screenshot 2024-10-29 at 19 55 24" src="https://github.com/user-attachments/assets/8ad76068-868e-42a7-830a-71505cb022fd">

Change the URL of this page to: https://app.moneyfitt.co/start

Right now we have this page and the actual sign in page using the same URL

**Comment by yeaung276** [comment]
In the lander page, redirect to `app.moneyfitt.co/onboarding?state=login`
