### ISSUE TITLE
Connect vercel to dev branch github and dev branch superbase

### ISSUE THREAD

**Issue by MikeBorman1** [Growthautomation/moneyfitt#161]
Branches are all set up, I think you need to just configure env variables in vercell for "preview" dev branch already built in https://vercel.com/mikeborman1s-projects/moneyfitt/GCEsFZ8Y9u6da2k7ZGSuJ4x9K7nm

Superbase also branched

we should remove all advisors from dev branch as to not send out emails accidentally

**Comment by yeaung276** [comment]
All setup. Gmail login will not be available as it require us to reverified the new supabase url for staging

**Comment by yeaung276** [comment]
`https://staging-moneyfitt.vercel.app/advisor/sign-in`
