### ISSUE TITLE
Testimonial

### ISSUE THREAD

**Issue by jackmoneyfitt** [Growthautomation/moneyfitt#168]
<img width="546" alt="Screenshot 2024-11-04 at 14 50 44" src="https://github.com/user-attachments/assets/45a82eeb-a95d-4ccf-b9fc-2d58bec007e5">

Format it to be two boxes (per testimonial):
1) Testimonial
2) Author 

E.g. 

_“We met when we were still in JC and I was straight away impressed with his cordial attitude. Behind this happy-go-lucky persona, there’s this driven personality that always strives to do the best of everything. This is evident throughout his life and career – achieving scholarships and multiple recognitions in the Air Force.  This positive attitude has been presented again during his advices on financial products. Always listening and understanding first before advising what are the relevant products that suits me more. It’s a very comfortable process and I know I can rely on his professionalism and expertise.“_
**Marvis, Director BT Sports**

**Comment by MikeBorman1** [comment]
We dont need to create a separate db field for this just UI I think
