### ISSUE TITLE
Change Company

### ISSUE THREAD

**Issue by jackmoneyfitt** [Growthautomation/moneyfitt#170]
<img width="624" alt="Screenshot 2024-11-04 at 15 16 16" src="https://github.com/user-attachments/assets/1c3aef92-a7a1-41d2-b34e-2635fe4afb24">

This should not be a list to select from!! Just allow them to type anything

**Comment by MikeBorman1** [comment]
Cant do this currently, will implement when we do a proper onboarding flow
