### ISSUE TITLE
Image Upload Failure

### ISSUE THREAD

**Issue by jackmoneyfitt** [Growthautomation/moneyfitt#194]
Trying to upload this image to Marcus Tan profile. [JPEG, 4.8mb, 5712 × 4284] 

![IMG_2946 2 - Marcus Tan](https://github.com/user-attachments/assets/8873707b-f909-426e-8dc1-3d34151eed2d)

I cannot upload it but do not know why - please find cause - we give no guidance to users on what will and won't be accepted

<img width="725" alt="Screenshot 2024-11-05 at 15 51 47" src="https://github.com/user-attachments/assets/26c0180d-ba33-48e8-9d78-ee48d748932e">

Also please introduce the ability to remove a picture from the slider with an X - I tested out another image and now can't remove it hahah

**Comment by MikeBorman1** [comment]
I dont understand, you just unselect the image?

**Comment by jackmoneyfitt** [comment]
I mean to get rid of it entirely
