### ISSUE TITLE
Legal Footer

### ISSUE THREAD

**Issue by MikeBorman1** [Growthautomation/moneyfitt#25]
We’ll need some sort of footer to the application with all the legal stuff for user assurance and compliance. Disclaimer about not being financial advice, company name, etc.

**Comment by yeaung276** [comment]
<img width="1293" alt="Screenshot 2567-10-09 at 11 17 05" src="https://github.com/user-attachments/assets/0b890fd5-b0a0-49e6-96ed-6b0e2511b284">
Here is initial version of the footer.
