### ISSUE TITLE
Redirect from switching google accounts

### ISSUE THREAD

**Issue by jackmoneyfitt** [Growthautomation/moneyfitt#33]
![IMG_5175](https://github.com/user-attachments/assets/6c733980-494e-47c6-872f-b71626aa6899)

Error after going through the following sequence:

Onboarding questions > sign in with google > selected one of my google accounts > got prompted for password and then realised it was the wrong google account > clicked back to choose the desired google account > got hit with error code

**Comment by yeaung276** [comment]
will close this since we can no longer reproduce this. will open again if happen again.
