### ISSUE TITLE
Finishing the onboarding form

### ISSUE THREAD

**Issue by MikeBorman1** [Growthautomation/moneyfitt#4]
- [x] All questions should default be required, so you cannot hit next button until something is selected.

- [x] Religion questions should be multiple-select
- [x] Age of advisor should be multiple select, text should say "Do you have any preference in your advisors age"
- [x] If user knows what they need ask age question first like on other branch

- [x] language, religion, company, advisor age these are all optional, the next button should say skip and then change to next if an option is selected

- [x] The progress bar needs fixing

**Comment by MikeBorman1** [comment]
Also needs to use same colour scheme as rest of site i.e the puples, we should have all buttons have same colour and on hover as the buttons on advisor card

**Comment by MikeBorman1** [comment]
check figma for full change log in the gray https://www.figma.com/board/PaCefOJa81rGwEqXwMNsog/Expert-Matching-Function?node-id=0-1&node-type=canvas&t=uldVoXqkp7UQfPdz-0

**Comment by yeaung276** [comment]
commit: 16d2ec1de7963248b9090e46b45edc30d0a937d5
