### ISSUE TITLE
Title of Blogs

### ISSUE THREAD

**Issue by jackmoneyfitt** [Growthautomation/moneyfitt#56]
<img width="720" alt="Screenshot 2024-10-11 at 17 18 21" src="https://github.com/user-attachments/assets/3ab24779-0b86-409e-922c-9cb19a90d49e">

Should be "Protect Your Family's Future with Lasting Power of Attorney (LPA)" ie no capital S and missing '

There are other blog titles that are missing things like colons or commas

+ capitalisation not transferred over correctly

**Comment by MikeBorman1** [comment]
This is from pulling the title from the slug, so loss of punctuation, need a better fix for content really
