### ISSUE TITLE
Reassurance message on first chat

### ISSUE THREAD

**Issue by jackmoneyfitt** [Growthautomation/moneyfitt#58]
<img width="1422" alt="Screenshot 2024-10-13 at 10 04 05" src="https://github.com/user-attachments/assets/f27704e8-03ab-47ac-af2e-e75fc778523d">

We could do with a preset message when they first open the chat:
- Reminding them that their data is secure
- Reassurance that their identity is anonymous 
- And some sort of positive message to gently push them to take action 

I have not decided on the msg so happy to keep this open until I have

**Comment by MikeBorman1** [comment]
![image](https://github.com/user-attachments/assets/b6de7d4d-bf4b-41f2-9bd2-34234b34acf4)
