### ISSUE TITLE
[UX] Go back button

### ISSUE THREAD

**Issue by jackmoneyfitt** [Growthautomation/moneyfitt#64]
<img width="1414" alt="Screenshot 2024-10-14 at 17 39 23" src="https://github.com/user-attachments/assets/c08f94c6-5cde-4f6b-b72f-4bb3670c853f">

Users do need to be able to go back here

**Comment by yeaung276** [comment]
commit: 8635cbaae6264f9948007d3a0c48fd1270ec9c6c

**Comment by yeaung276** [comment]
<img width="772" alt="Screenshot 2567-10-18 at 10 56 43" src="https://github.com/user-attachments/assets/566a854c-23e5-436d-9dfa-05b781c96602">
