### ISSUE TITLE
Integrate automated emails for Match and for message using SES or Sendgrid

### ISSUE THREAD

**Issue by MikeBorman1** [Growthautomation/moneyfitt#7]

**Comment by MikeBorman1** [comment]
Unique Sender Address:
Format: Use a unique email address for each advisor and user based on the match. Example: matchID@platform.com.

this is what upwork does
![image](https://github.com/user-attachments/assets/b8ab6042-0711-478f-bcef-550793225748)
![image](https://github.com/user-attachments/assets/3e4d7b8d-ab44-4387-8a89-10d2b4ed4f81)


For Messages:
Check User Activity:
If the user (either advisor or user) is active, do not send an email.
If the user is inactive, send the email.

Threaded Emails:
Use the same subject line for all messages within the match thread, ensuring the emails are grouped as replies in the inbox.


Real-Time Monitoring - not sure how best to do this but just a suggestion
Keep track of when a user is logged in or has recently interacted with the platform.
Avoid sending notifications within a specific window after activity (e.g., 5-10 minutes of recent activity).

**Comment by yeaung276** [comment]
#49
