### ISSUE TITLE
Ability to Go Back 

### ISSUE THREAD

**Issue by jackmoneyfitt** [Growthautomation/moneyfitt#78]
<img width="1228" alt="Screenshot 2024-10-18 at 11 44 22" src="https://github.com/user-attachments/assets/ee330bc1-5131-4bc0-a008-46584904955d">

**Comment by yeaung276** [comment]
commit: 8635cbaae6264f9948007d3a0c48fd1270ec9c6c

**Comment by yeaung276** [comment]
<img width="894" alt="Screenshot 2567-09-25 at 15 29 23" src="https://github.com/user-attachments/assets/5d1d3a41-4391-461d-85e3-691cc478a2ce">
