### ISSUE TITLE
UI/UX on chatbot to match rest of site + fix bugs

### ISSUE THREAD

**Issue by MikeBorman1** [Growthautomation/moneyfitt#8]
make it look the same as other cards

+ UI bugs
- [ ] Sometimes prompt cards overlap messages
- [x] prompt cards when clicked do not populate the text field
- [x] text field needs to expand when there are new lines vertically

**Comment by yeaung276** [comment]
commit: 42646fed47c2bb5ee415aaa433d80928619178ba
