### ISSUE TITLE
Redo the task of making the profiles believable 

### ISSUE THREAD

**Issue by jackmoneyfitt** [Growthautomation/moneyfitt#86]
The 3 listed profiles I can see (Jake Lim, Sarah Lee, Emily Chen) are incomplete and boring, we need to use these for our marketing so they have to be believable and interesting.

Add profile pictures (unsplash or pexels)

Add images at the bottom of the profile 

Make the bio, professional background, certifications, and testimonials all believable and interesting.

**Comment by yeaung276** [comment]
won't do
